name: CI - Build & Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u balamadhavan --password-stdin

      - name: Build Docker image
        run: docker build -t balamadhavan/task1:latest .

      - name: Push Docker image
        run: docker push balamadhavan/task1:latest
